name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.2'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
          
      - name: Install Composer dependencies
        run: composer install
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.2'
          
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
          
      - name: Install Composer dependencies
        run: composer install
        
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install npm dependencies
        run: npm install

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
